divide

diff --git a/init_files_variables_and_expansions/9-divide_and_rule b/init_files_variables_and_expansions/9-divide_and_rule
--- a/init_files_variables_and_expansions/9-divide_and_rule
+++ b/init_files_variables_and_expansions/9-divide_and_rule
@@ -1,2 +1,2 @@
 #!/bin/bash
-result=$((POWER / DIVIDE))
+echo $(( POWER / DIVIDE )) || echo "Error: Division by zero or variable not set."
